default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ventrata_api_dummy_app_development

test:
  <<: *default
  database: ventrata_api_dummy_app_test
